"""Init database

Revision ID: 9fac8806e9a8
Revises:
Create Date: 2026-03-10 17:26:47.144736

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fac8806e9a8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blackjack_tracking_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="blackjacktrackingtaskstatus",
            ),
            nullable=False,
        ),
        sa.Column("csv_output_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_blackjack_tracking_task_status"),
        "blackjack_tracking_task",
        ["status"],
        unique=False,
    )
    op.create_table(
        "blackjack_game_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["blackjack_tracking_task.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blackjack_game_session")
    op.drop_index(
        op.f("ix_blackjack_tracking_task_status"), table_name="blackjack_tracking_task"
    )
    op.drop_table("blackjack_tracking_task")
    # ### end Alembic commands ###
